---
- name: Install dependencies for mako
  package:
    name: "{{ mako_deps }}"
    state: present
  become: true

- name: Make sure the src_dir exists
  file:
    path: "{{ src_dir }}/mako"
    state: directory
    recurse: yes

- name: Clone the mako project
  git:
    repo: https://github.com/emersion/mako
    dest: "{{ src_dir }}/mako"
    force: true
    update: "{{ upgrade | default(false) }}"

- name: Run meson build
  command:
    cmd: "meson build"
    chdir: "{{ src_dir }}/mako"
  changed_when: false

- name: Install using ninja
  command:
    cmd: "sudo ninja -C build install"
    chdir: "{{ src_dir }}/mako"
    warn: false
  changed_when: false
