---
- name: Install dependencies for Wofi
  package:
    name: "{{ wofi_deps }}"
    state: present
  become: true

- name: Make sure the src_dir exists
  file:
    path: "{{ src_dir }}/wofi"
    state: directory
    recurse: yes

- name: Clone the wofi project
  hg:
    repo: https://hg.sr.ht/~scoopta/wofi
    dest: "{{ src_dir }}/wofi"
    force: true
    update: "{{ upgrade | default(false) }}"

- name: Run meson build
  command:
    cmd: "meson build"
    chdir: "{{ src_dir }}/wofi"
  changed_when: false

- name: Install using ninja
  command:
    cmd: "sudo ninja -C build install"
    chdir: "{{ src_dir }}/wofi"
    warn: false
  changed_when: false

- name: Copy the wofi config files over
  copy:
    src: files/wofi
    dest: "$HOME/.config/"
